### ISSUE TITLE
Having problems to run it vs MediaMTX

### ISSUE THREAD

**Issue by neilyoung** [kevmo314/whep-to-whip#1]
I'm wondering if your proxy sample is kind of general purpose. I'm publishing a video to a MediaMTX instance using WHIP and I'm able to fetch it using WHEP.

Tried your proxy OOB to re-publish my WHIP source to another stream to no avail. Added a print of the received offer and got this:

```
024/11/11 21:47:53 Offer &{Status:400 Bad Request StatusCode:400 Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Access-Control-Allow-Credentials:[true] Access-Control-Allow-Origin:[*] Content-Length:[32] Content-Type:[application/json; charset=utf-8] Date:[Mon, 11 Nov 2024 20:47:53 GMT] Server:[nginx/1.18.0 (Ubuntu)]] Body:{cs:0x140000fc180} ContentLength:32 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:0x140000005a0 TLS:0x140000fa0b0}
```

The following code fails in advance:

```
2024/11/11 21:47:53 location: 
panic: Patch "": unsupported protocol scheme ""

goroutine 1 [running]:
main.main()
	/Users/me/Documents/tmp/whep-to-whip/main.go:48 +0x388
exit status 2
```

**Comment by kevmo314** [comment]
Yes, it's general purpose. The error message seems to suggest mediamtx isn't setting the location header? I tested it with mediamtx when I first created the repo so it should work although I know the standards have changed a bit. 

Are you running against the latest version of mediamtx?

**Comment by kevmo314** [comment]
Ah it seems indeed the spec has changed enough so this is not quite as trivial anymore. It should still be possible but the code needs to be updated. 

https://www.ietf.org/archive/id/draft-murillo-whep-03.html#name-ice-and-nat-support

**Comment by neilyoung** [comment]
Don't bother. No issue

**Comment by dhirajdhule** [comment]
@kevmo314 Would you be able to share some tips on what needs to be done as per the new spec? Thanks in advance.

**Comment by kevmo314** [comment]
> @kevmo314 Would you be able to share some tips on what needs to be done as per the new spec? Thanks in advance.

The code needs to be updated to add the `If-Match` header the document suggests. In particular, it looks like under the new spec the general order of operations will be:

1. POST an empty offer SDP to WHEP endpoint to get the answer SDP, signal trickle ICE so the connection does not establish yet.
2. POST the WHEP answer SDP to the WHIP endpoint as an offer, get the answer SDP with the ICE candidates.
3. PATCH the WHEP endpoint with the WHIP SDP's ICE candidates under trickle ICE to establish the connection.

This will let the WHEP data flow directly to WHIP. It should still work but is perhaps not as easy as the initial repo would suggest anymore.

**Comment by dhirajdhule** [comment]
Thanks for the quick response. 

Seems like Dolby doesn't allow POSTing an empty offer SDP to WHEP endpoint. I got a 406 error. I will dig more. 

I am assuming in such a case I could create a SDP offer first and then start the conversation. 

I am trying to WHEP from Dolby and WHIP into MediaMTX.

**Comment by kevmo314** [comment]
> Thanks for the quick response.
> 
> Seems like Dolby doesn't allow POSTing an empty offer SDP to WHEP endpoint. I got a 406 error. I will dig more.
> 
> I am assuming in such a case I could create a SDP offer first and then start the conversation.
> 
> I am trying to WHEP from Dolby and WHIP into MediaMTX.

Yeah I think you would need to create an SDP offer that contains potentially invalid candidates. In some sense, trick the WHEP server into giving you an SDP which you can then send to WHIP and then take advantage of trickle ICE.

In the earlier version of the WHEP spec this was actually the standard pattern (server-generated offers) but it seems like that is no longer the case.

**Comment by neilyoung** [comment]
I'm doing it in GOLANG using PION and having a WHEP to WHIP proxy which proxies plain RTP. It establishes the WHEP connection first, sending an OFFER and receiving the ANSWER. My offer contains the desired codec and gathered candidates (STUN only atm). Once I have the track I'm doing the same towards the WHIP server, now not sending any ICE candidate in my OFFER. Once this is up I'm starting the RTP shovel :) In between I'm noticing the Locations returned from both to cleanly release both sessions once the source goes. MediaMTX in this scenario is the WHEP endpoint. WHIP is done by a Mediasoup instance, which I have made "WHIP capable". 

If required I can fire up a session and share the SDP going back and forth. Cannot share code, since it is closed source.

**Comment by kevmo314** [comment]
> I'm doing it in GOLANG using PION and having a WHEP to WHIP proxy which proxies plain RTP. It establishes the WHEP connection first, sending an OFFER and receiving the ANSWER. My offer contains the desired codec and gathered candidates (STUN only atm). Once I have the track I'm doing the same towards the WHIP server, now not sending any ICE candidate in my OFFER. Once this is up I'm starting the RTP shovel :) In between I'm noticing the Locations returned from both to cleanly release both sessions once the source and/or destination goes. MediaMTX in this scenario is the WHEP endpoint. WHIP is done by a Mediasoup instance, which I have made "WHIP capable".
> 
> If required I can fire up a session and share the SDP going back and forth. Cannot share code, since it is closed source.

The downside to this approach though is your proxy has to receive and send all the RTP data which can be quite a lot of bandwidth. The original motivation for this repo was to demonstrate a trick with WHEP/WHIP where the proxy doesn't use any bandwidth.

**Comment by neilyoung** [comment]
The aim behind was to forward video from an RTSP source to Mediasoup. Mediasoup needs video in a push-manner out of the box, it might be possible with some trick to make it fetch RTSP, but my source is not publicly available at RTSP level, so now way. Now my RTSP is pushing to MediaMTX locally, MediaMTX is making the transition from RTSP to WebRTC. My W2W proxy is running on the same server, so it's all local traffic on an edge device and from there it goes out. All RTP overhead is "localhost", no need to worry. It solved a particular problem I had and all other solutions only forced me to transcode or at least re-encode the RTSP source video.
